name: Deploy Staging
on:
  push:
    branches:
      - dev
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          token: ${CODECOV_TOKEN} # not required for public repos
          fail_ci_if_error: true # optional (default = false)
